server:
  port: ${PORT:0}

spring:
  application:
    name: album-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance-id:${random.value}}
    prefer-ip-address: true